# Generated by Django 3.0.7 on 2020-07-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200630_0735'),
        ('order', '0002_auto_20200701_0729'),
        ('account', '0002_account_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='product',
        ),
        migrations.AddField(
            model_name='account',
            name='product_color',
            field=models.ManyToManyField(through='order.CartWishlist', to='product.ProductColor'),
        ),
    ]
