# Generated by Django 3.0.7 on 2020-06-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
