# Generated by Django 3.0.7 on 2020-06-29 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_delete_thumnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product_color',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
