# Generated by Django 3.0.7 on 2020-07-03 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200630_0735'),
        ('product', '0011_auto_20200629_1458'),
    ]

    operations = [
    ]
