# Generated by Django 3.0.7 on 2020-06-30 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200625_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytype',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menu.MenuCategory'),
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='type_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menu.TypeName'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menu.Category'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='menu',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='menu.Menu'),
        ),
    ]
