# Generated by Django 3.0.7 on 2020-07-03 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200630_0257'),
        ('menu', '0003_auto_20200628_0502'),
    ]

    operations = [
    ]
